x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env.airflow
  environment:
    &airflow-common-env
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__INTERNAL_API_URL: "http://airflow-apiserver:8080"
    AIRFLOW__WORKERS__BASE_URL: "http://airflow-apiserver:8080"
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution"
    # Jobs path (dentro il container Spark)
    SPARK_JOBS_PATH: "/opt/spark/jobs"
    HOST_JOBS_PATH: "${PWD}/pipeline/jobs"

  volumes:
    - ./pipeline/dags:/opt/airflow/dags
    - ./pipeline/logs:/opt/airflow/logs
    - ./pipeline/data:/opt/airflow/data
    - /var/run/docker.sock:/var/run/docker.sock  # DockerOperator

  depends_on:
    &airflow-common-depends-on
    postgres-airflow:
      condition: service_healthy
    redis:
      condition: service_healthy

services:

  postgres-airflow:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-airflow-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - crypto-net

  postgres-data:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_password
      POSTGRES_DB: crypto_data
    volumes:
      - postgres-data-db:/var/lib/postgresql/data
      - ./postgres/postgres.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres/init-replication.sql:/docker-entrypoint-initdb.d/init-replication.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "crypto_user"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - crypto-net

  redis:
    image: redis:7.2-bookworm
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - crypto-net

  airflow-init:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: on-failure
    networks:
      - crypto-net

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
      interval: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - crypto-net

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    networks:
      - crypto-net

  airflow-worker:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || exit 1'
      interval: 30s
      retries: 5
      start_period: 30s
    restart: always
    deploy:
      replicas: 2
    networks:
      - crypto-net

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type DagProcessorJob --hostname $(hostname)"]
      interval: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - crypto-net

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type TriggererJob --hostname $(hostname)"]
      interval: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - crypto-net

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: custom-spark:latest
    container_name: spark-master
    hostname: spark-master
    env_file:
      - .env.spark
    environment:
      - SPARK_LOCAL_IP=spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip 0.0.0.0 --port 7077 --webui-port 8080
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./pipeline/jobs:/opt/spark/jobs
    restart: always
    networks:
      - crypto-net

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: custom-spark:latest
    hostname: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    env_file:
      - .env.spark
    environment:
      - SPARK_LOCAL_IP=spark-worker
    volumes:
      - ./pipeline/jobs:/opt/spark/jobs
    depends_on:
      - spark-master
    restart: always
    deploy:
      replicas: 3
    networks:
      - crypto-net

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - crypto-net

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      sh -c "
        mc alias set local http://minio:9000 minio_admin minio_password &&
        mc mb --ignore-existing local/bronze &&
        mc mb --ignore-existing local/silver &&
        mc mb --ignore-existing local/gold &&
        mc mb --ignore-existing local/mlflow &&
        echo 'Bucket creati!'
      "
    restart: on-failure
    networks:
      - crypto-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: always
    networks:
      - crypto-net

  kafka-connect:
    image: debezium/connect:3.0.0.Final
    depends_on:
      - kafka
      - postgres-data
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: debezium-group
      CONFIG_STORAGE_TOPIC: debezium_configs
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    restart: always
    networks:
      - crypto-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
    depends_on:
      - kafka
      - kafka-connect
    restart: always
    networks:
      - crypto-net

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio_admin
      AWS_SECRET_ACCESS_KEY: minio_password
    command: >
      mlflow server
      --backend-store-uri postgresql://crypto_user:crypto_password@postgres-data/crypto_data
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
      --port 5000
    depends_on:
      - postgres-data
      - minio
    restart: always
    networks:
      - crypto-net

  # Notebooks to analyze data
  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      SPARK_MASTER: "spark://spark-master:7077"
      AWS_ACCESS_KEY_ID: minio_admin
      AWS_SECRET_ACCESS_KEY: minio_password
      AWS_ENDPOINT_URL: http://minio:9000
    volumes:
      - ./pipeline/notebooks:/home/jovyan/work
    depends_on:
      - spark-master
      - minio
    restart: always
    networks:
      - crypto-net
volumes:
  postgres-airflow-db:
  postgres-data-db:
  minio-data:
  kafka-data:

networks:
  crypto-net:
    driver: bridge
    name: crypto-net