CREATE USER debezium WITH REPLICATION LOGIN PASSWORD 'debezium_password';
GRANT CONNECT ON DATABASE crypto_data TO debezium;
GRANT USAGE ON SCHEMA public TO debezium;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO debezium;
CREATE PUBLICATION debezium_publication FOR ALL TABLES;